# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7100d944a343385da3eac30be8d727359216afd615575318024c2199a15b9fbb9dff9f02c01cd388c0ab5171382246be329477563881fe6d3db7a79b533f386

test:
  secret_key_base: ca4c22f952efc03cc06872cd9a5eee1d37b1328485a788a2eaac6cc0f08c937769ac2de4d857c640f39980e152123772753ddee9efc895d41c5f67a8fecdb883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
